version: '2'

services:
  apache:
    build: .
    volumes:
      - ./app:/var/www/elite-cloud/app
    ports:
      - '80:80'
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: elitecloud
      MYSQL_ROOT_PASSWORD: 123456